### PR TITLE
Create CherryPy Submit server & updated client submit script

### PR DESCRIPTION
**Pull request by jjhursey**
* Create a CherryPy server
   - Provides a JSON REST interface for submitting results
 * Create a Perl Reporter Module (`MTTStorage`) to submit to this interface
 * Update the Python Reporter Module (`IUDatabase`) to submit to this interface

API is documented here:
  https://github.com/jjhursey/mtt-modern/wiki/REST-Interface-(Submit-Side)

### CODE REVIEW

**Comment by rhc54** [comment]
@noahv Just pointing Noah to your PR - please let us know how we can be of help!

**Comment by jjhursey** [comment]
I think I'll need some help finishing the IUDatabase file. If you search for JJH in the IUDatabase file you will see a set of fields all set to `None`. We will need to figure out the best way to fill in these values based upon what the Python client has collected (we might need to track some more information).

```
shell$ grep -n JJH pylib/Stages/Reporter/IUDatabase.py
177:		# JJH Todo fill these fields in
255:		# JJH Todo fill these fields in
308:		# JJH Todo fill these fields in
```

I'll try to get some more cycles to work on this in the next few days, but if you have some cycles to pick away at it that would help. Once those fields are filled then then we should be all set.

I'm working on setting up the new cherrypy service on `mtt.open-mpi.org`. It needs some installs, so it might not be until early next week that the service will be active.

**Comment by rhc54** [comment]
@jjhursey I see one problem - we don't record the final parameters used to execute the section. I'll update that so we do.

I'm not sure what some of these other fields mean - e.g., mpi_install_id? Is that a character string of the stage that installed the MPI being used?

Perhaps a phone call could help clarify those?

**Comment by rhc54** [comment]
@jjhursey Okay, I pushed a change (open-mpi/mtt@54b2e7be42d4e82631e72a04b50784bd12970d68) that records the final stage options (i.e., the parsed combination of default options and provided input params) as a dictionary called 'options' in the log. This will contain much of the info you were asking for, so I think what is left is for us to decide on the meaning of the remaining fields.

**Comment by jjhursey** [comment]
@rhc54  The `mpi_install_id` will be one of the parameters passed back by the server along with the `submit_id` (and some other ids). So those just need to be handed back to the server, if the client still has them. I should writeup some documentation on that interface.

I have the server running here:
   https://mtt.open-mpi.org/submit/cpy/api/
Use the same credentials that you would use for the normal IU submit database. It will submit to the IU database so you can see the results in the Reporter - although everything is marked as 'trial'.

I'll look at the change today, and see if I can't match up some of the fields. Then it would probably be good to have a phone call about any remaining items.

**Comment by jjhursey** [comment]
I added some documentation on the fields here:
  https://github.com/jjhursey/mtt-modern/wiki/REST-Interface-(Submit-Side)

It includes example input/output.

**Comment by jjhursey** [comment]
I would like to merge this into the master branch since most of the backend work is finished, along with the Perl client plugin. The Python plugin will require some iteration which is happening primarily on the master branch.

@rhc54 What do you think?

**Comment by rhc54** [comment]
Please do! Much appreciated

**Pull request merged**
