### PR TITLE
Combinatorial retry

### PR DESCRIPTION
**Pull request by DebRez**
Basic working version of the combinatorial executor.

combinatorial execution can be started on the command line with --executor combinatorial or in the configuration file in the MTTDefaults section with executor = combinatorial.

Here is the file used to test the code so far.
[combinatorialTest.txt](https://github.com/open-mpi/mtt/files/600480/combinatorialTest.txt)

### CODE REVIEW

**Comment by noahv** [comment]
Hi Deb,

Will you please update this pull request to allow for .ini files to not specify an executor and have it default to the sequential exe?

Here is the code:

iff --git a/pyclient/pymtt.py b/pyclient/pymtt.py
index d5be3e0..3b999db 100755
--- a/pyclient/pymtt.py
+++ b/pyclient/pymtt.py
@@ -250,11 +250,15 @@ testDef.openLogger()
 testDef.configTest()
 
 # Determine executor to use
-if (testDef.config.get("MTTDefaults","executor") == "sequential" or testDef.config.get("MTTDefaults","executor") == "Sequential"):
+try:
+    if (testDef.config.get("MTTDefaults","executor") == "sequential" or testDef.config.get("MTTDefaults","executor") == "Sequential"):
+        testDef.executeTest()
+    elif (testDef.config.get("MTTDefaults","executor")== "combinatorial" or testDef.config.get("MTTDefaults","executor") == "Combinatorial"):
+        testDef.executeCombinatorial()
+    else:
+        print("Specified executor ", testDef.args.executor, " not found!")
+        sys.exit(1)    
+except:
+    # Run the sequential executor if not specified in the MTTDefaults section
     testDef.executeTest()
-elif (testDef.config.get("MTTDefaults","executor")== "combinatorial" or testDef.config.get("MTTDefaults","executor") == "Combinatorial"):
-    testDef.executeCombinatorial()
-else:
-    print("Specified executor ", testDef.args.executor, " not found!")
-    sys.exit(1)    
 # All done!

**Comment by noahv** [comment]
Also, please remove these extra prints; I don't think they were intended:

```
diff --git a/pylib/Utilities/Logger.py b/pylib/Utilities/Logger.py
index 436c493..57ff401 100644
--- a/pylib/Utilities/Logger.py
+++ b/pylib/Utilities/Logger.py
@@ -81,8 +81,6 @@ class Logger(BaseMTTUtility):
 
     def verbose_print(self, str):
         if self.printout:
-            for item in str:
-                print(item)
             print(str, file=self.fh)
         return
```

**Comment by DebRez** [comment]
I made the fixes you requested Noah.

**Comment by jsquyres** [comment]
@noahv Github pro tip: you can add a token after the first 3 single ticks (for github verbatim mode) to tell Github what syntax highlighting to use.  For example, if you put the token "patch" (without the quotes) after the first 3 single ticks, it will syntax highlight your verbatim block as a patch.  I updated your first comment here on this PR to include the "patch" token so that you can see what it looks like.  You can also use a variety of language names, like "c", "python", etc.

**Comment by jsquyres** [comment]
@DebRez One of the commits in your sequence has an incorrect "Signed-off-by" line (it has "Signed off by" instead of the correct "Signed-off-by").  You can use an interactive git rebase (i.e., `git rebase -i ...`) to fix this, and then force push back up to your branch (note: this is just about the *only* time it's acceptable to force push!).

**Comment by noahv** [comment]
Thanks Jeff.  Nifty!

**Comment by noahv** [comment]
Hi Deb,

We still get a backtrace when using the latest change set you put in place for supporting executing without specifying the executor.

``
Traceback (most recent call last):
  File "/opt/mtt/pyclient/pymtt.py", line 256, in <module>
    elif (testDef.config.get("MTTDefaults","executor") == "sequential" or testDef.config.get("MTTDefaults","executor") == "Sequential"):
  File "/usr/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'executor' in section: 'MTTDefaults'
``

Initially, I also looked at using the DefaultMTTDefaults.py default value of "sequential" as you did in the current patch but unfortunately that didn't work.

Would the patch set I pasted above with the try / except work for you instead?

Thanks,

  -- Noah

**Comment by DebRez** [comment]
I will work on this and the Sign off issue on Wednesday.

Deb

**Comment by DebRez** [comment]
I have updated the commit.

**Comment by noahv** [comment]
Hi Deb,

Good news most of my tests now pass on this topic branch.  

However, there is one additional issue that looks like some debug experiments that ended up in the patch and is causing failures.  Here is the patch:

```patch
diff --git a/pylib/Utilities/ExecuteCmd.py b/pylib/Utilities/ExecuteCmd.py
index 0d17a06..56ef7a7 100755
--- a/pylib/Utilities/ExecuteCmd.py
+++ b/pylib/Utilities/ExecuteCmd.py
@@ -94,6 +94,11 @@ class ExecuteCmd(BaseMTTUtility):
                     # if the data
                     if fd == p.stdout.fileno():
                         read = p.stdout.readline().rstrip()
+                        testDef.logger.verbose_print('stdout: ' + read.decode("utf-8", errors='replace'))
+                        if merge:
+                            stderr.append(read.decode("utf-8", errors='replace'))
+                        else:
+                            stdout.append(read.decode("utf-8", errors='replace'))
                     elif fd == p.stderr.fileno():
                         read = p.stderr.readline().rstrip()
                         testDef.logger.verbose_print('stderr: ' + read.decode("utf-8", errors='replace'))
```

**Comment by noahv** [comment]
Please also note that this topic branch is behind the master fork by a couple of commits:

```
9956c823677861286d571270dd92b8cbec781a71 Merge pull request #482 from noahv/topic/git_branch
d97ae44199cdad3774185961a7e4de411a3e8ec9 Added git branch support. Moved sample hello world srun based execution to v1.10.
```

That is not a big deal and will be taken care of when we merge the pull request.  It does however, cause the older version of samples/python/ompi_hello_world.ini to fail in your topic branch.

In general, it is best to rebase your topic branch when needed:

**Rebasing your topic branch with an upstream updated master**
```
# Tuck away any changes that you have not committed
git stash 
# Synchronize with the upstream updates; upstream remote previously added with 
# git remote add upstream https://github.com/open-mpi/mtt.git
git fetch upstream
git checkout master
git merge upstream/master
git push origin master 
# Jump back to your branch
git checkout topic/<name of your topic>
git rebase master
git stash apply 
# Fix any conflicts that may have resulted
# Force push your updates to the topic branch
git push --force origin topic/<name of your topic>
```

Thanks again for you work getting this enabled!  -- Noah

**Comment by DebRez** [comment]
I fixed ExecuteCmd.py and rebased using your very helpful instructions. 
Thanks for your patience Noah --Deb

**Pull request merged**
