### PR TITLE
Added np to log

### PR DESCRIPTION
**Pull request by DebRez**
OpenMPI.py now has an entry for "np"

This fixes issue #464 

Signed-off-by: Deb Rezanka <drezanka@newmexicoconsortium.org>

@ribab 
@rhc54 
@hppritcha

### CODE REVIEW

**Comment by rhc54** [comment]
I think the logic looks fine, but the indentation is wrong?

**Comment by DebRez** [comment]
I use emacs and it looks fine there but I opened it in vim and was able to
see and fix the problem.  I will check my indentation rules in emacs and
see if I set something wrong but this hasn't happened before.  Any ideas
what may cause emacs and vim to show spacing differently?

**Comment by DebRez** [comment]
fixed spacing

**Comment by rhc54** [comment]
Check your tabs settings. We ask that everyone set their editors to replace tabs with spaces, and set the mapping to 4 spaces/tab stop. It's likely one of those that's the issue.

**Pull request merged**
