### PR TITLE
Fixed fields passed into reporter

### PR DESCRIPTION
**Pull request by ribab**
Reporter wasn't working since some fields were passed in as lists. I fixed this by joining the lists together.

I also realized that the "result_stderr" bad-format problem wasn't occurring. Maybe that bug was already fixed. -- Bug #468

### CODE REVIEW

**Comment by ribab** [comment]
It says that my commit wasn't signed off. I'll fix that later

**Comment by jjhursey** [comment]
So you are able to submit to the MTT server just fine now?

**Comment by ribab** [comment]
I didn't test against an official MTT server. I tested against locally hosted DB and Cherrypy server.

**Comment by ribab** [comment]
It should be good to merge now. I fixed the signing error.

**Pull request merged**
