### PR TITLE
Add exception list in rules of include_section processing

### PR DESCRIPTION
**Pull request by igor-ivanov**
Original processing ignores parameters in include section if
they exist in base section.
There are cases when it is useful to accept parameters from both sections.
Added list of parameters that may be taken from base and include sections.
Example:

[section common]
setenv value1
setenv value2

[section_debug]
include_setion = section common
setenv debug

[section_release]
include_section = section common

### CODE REVIEW

**Comment by igor-ivanov** [comment]
@jsquyres - please review

**Comment by miked-mellanox** [comment]
even more, the include section should be always applied as-is BEFORE the including section.
If both sections contain same params (np, setenv, pass) - the latest used (from including section) will survive.

I think this is a expected behave.
@jsquyres , @igor-ivanov - please comment

**Comment by igor-ivanov** [comment]
It is important to understand that different parameters have various ways of processing.
For example np is a scalar when setenv is array.
This change affects parameters accepting array.
See example with env_module (it is a scalar) to understand that parameter from base section has highest priority.

**Comment by miked-mellanox** [comment]
got you now, thanks
looks good.

**Pull request merged**
