### PR TITLE
Script to prune the DB to a sliding window

### PR DESCRIPTION
**Pull request by jjhursey**
* Takes one argument the number of months to keep in the DB

### CODE REVIEW

**Comment by jjhursey** [comment]
I have this script running in a cron. I'd like to keep an eye on it for a couple of months before merging this PR just in case there is anything we need to tweek. For now it looks pretty good.

So I'll leave it in draft form until it's proven itself a bit more.

**Review by jsquyres — APPROVED** [review]
image

**Comment by jjhursey** [comment]
All the other maintenance scripts are in Perl so I'm just keeping the theme.

**Comment by jsquyres** [comment]
jen-yes

**Comment by jjhursey** [comment]
This script has been working great. Merging so we don't lose track of it.

**Pull request merged**
