### PR TITLE
Consolidated sample .ini files in mtt/samples.

### PR DESCRIPTION
**Pull request by DebRez**
fixes issue #454 

Signed-off-by: Deb Rezanka <drezanka@newmexicoconsortium.org>

@noahv 
@rhc54

### CODE REVIEW

**Comment by jjhursey** [comment]
This looks good. Can you grep around to see if any of the README files need to be updated to reflect the subdirectory change. I found this one, but there might be others:
  https://github.com/open-mpi/mtt/blob/master/README#L127

**Comment by ribab** [comment]
I'm waiting on this pull-request to go through before I make my pull-request because I will be editing the python INI files.

**Comment by DebRez** [comment]
@jjhursey 

Updated documentation per your request.

**Comment by jjhursey** [comment]
Thanks! 👍

**Pull request merged**
