### PR TITLE
Added support for checking disk and memory space

### PR DESCRIPTION
**Pull request by beardeddog**
This plugin allows you to configure checks for diskspace percent availble and
free, used or total memory (in gigs) against a threshold value.  Multiple
check can be done by comma separating them.

Signed-off-by: william.c.weide <william.c.weide@intel.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
That doesn’t look like a valid email address. 

Check you gmail and we can sync up - I can help you through the Github stuff.

**Comment by beardeddog** [comment]
@jsquyres - I got your email, thanks
I ended up re-cloning and re-making my changes again :(  and then opening a new pull request.

**Comment by jsquyres** [comment]
Still need to fix the email address on that commit, though (typing on phone; sorry for brevity)

**Comment by beardeddog** [comment]
Thanks @jsquyres for walking me through how to fix this ...

**Pull request merged**
