### PR TITLE
Fix Python Client submission to AWS

### PR DESCRIPTION
**Pull request by jjhursey**
* Fixes Issue #562
 * Working version of CherryPy is 8.9.0. Need to further investigate why later versions don't work with our configuration
 * Add `configparser` to the python client required environment
 * Ignore the `InsecureRequestWarning` to work around annoying warning message about the cert on the mtt server at AWS.

### CODE REVIEW

**Comment by rhc54** [comment]
Thanks @jjhursey !

**Comment by hppritcha** [comment]
woopie works for me if I patch for python3.

**Comment by hppritcha** [comment]
@ribab could we get this merged in?  I'd like to start using the python client for production testing soon and we need this for that to happen.

**Comment by ribab** [comment]
looks good to me so I'm merging.

**Pull request merged**
