### PR TITLE
Record the time it takes to execute each test

### PR DESCRIPTION
**Pull request by rhc54**
Do this by default, but allow someone to turn it off if they so choose

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres is seeing a problem where his system seems to be running tests very slowly. The tests are not timing out - they just appear to be running slow. However, the Perl client doesn't have a way of tracking execution time, and so we can't really verify that impression.

This would allow the Python client to track execution time of tests. We need a corresponding change to the database and viewer to allow that info to be recorded and displayed.

**Comment by noahv** [comment]
Hi Ralph,

Looks like python does not like the elapsed = end - start

```
Profile:Installed
Collect system profile
ExecuteCmd: uname -v
stdout: #1 SMP Wed Nov 11 20:52:43 UTC 2015 (8d714a0)
Traceback (most recent call last):
  File "/opt/mtt/pyclient/pymtt.py", line 273, in <module>
    testDef.executeTest()  
  File "/opt/mtt/pylib/System/TestDef.py", line 590, in executeTest
    executor.plugin_object.execute(self)
  File "/opt/mtt/pylib/Tools/Executor/sequential.py", line 230, in execute
    plugin.execute(stageLog, keyvals, testDef)
  File "/opt/mtt/pylib/Stages/Profile/DefaultProfile.py", line 70, in execute
    status, stdout, stderr, time = testDef.execmd.execute(cmds, self.options[key][2], testDef)
  File "/opt/mtt/pylib/Utilities/ExecuteCmd.py", line 125, in execute
    elapsed = end - start
TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'float'
```

**Comment by rhc54** [comment]
@noahv Please give it another try - I changed the names of the variables to avoid conflicts with reserved words

**Comment by noahv** [comment]
Hi Ralph, sorry for the delay I was off on spring break last week.

Looks like its just a typo:
```patch
--- a/pylib/Utilities/ExecuteCmd.py
+++ b/pylib/Utilities/ExecuteCmd.py
@@ -121,7 +121,7 @@ class ExecuteCmd(BaseMTTUtility):
                 if p.poll() != None:
                     break
             if time_exec:
-                endtime = time.time
+                endtime = time.time()
                 elapsed = endtime - starttime
 
         except OSError as e:
```

**Comment by noahv** [comment]
Were you going to update the reporters and the DB with the time?

**Comment by rhc54** [comment]
When I have a chance, I will do so - thanks for spotting the typo!

**Pull request merged**
