### PR TITLE
Remove GPL packages

### PR DESCRIPTION
**Pull request by rhc54**
Delete the GPL CPAN packages that were installed in the repo. Replace them with distro packages where possible:

sudo yum install perl-config-inifiles
sudo yum install perl-Email-Date-Format
sudo yum install perl-Env
sudo yum install perl-Filesys-Df
sudo yum install perl-MIME-Lite
sudo yum install perl-Text-Table-Tiny

I had to manually install Text::TabularDisplay using cpan

Required changes:

* replace references to Filesys::DiskFree with Filesys::Df. The resulting information is now stored in a hash, so update those references as well

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Also need to install JSON:

sudo yum install perl-JSON

My local testing has hit a speedbump as I gather the sample/perl ini files are no longer accurate when it comes to fetching the OMPI tarball. Can someone please update them, or tell me the required change and I'll do it? I seem to recall there was a change awhile back but these were missed

**Comment by rhc54** [comment]
Okay, I found the email that updated the URL and fixed the sample ini file. Now downloading and building OMPI tarballs just fine, but execution fails - I suspect due to a PATH issue. Will chase that down later.

**Comment by jsquyres** [comment]
Per 2018-09-11 webex, Ralph:

1. Created a new `open-mpi/mtt-legacy` repo
1. Pushed this repo into the new `mtt-legacy` repo
1. Deleted all the Python code from the new `mtt-legacy` repo

This PR will close the loop on the other side: remove all the Perl from the `mtt` repo.

Cisco switched over to using the `open-mpi/mtt-legacy` repo and everything is fine.  👍

**Comment by rhc54** [comment]
@bwbarrett Running up against a deadline - can you please confirm you are switched over?

**Comment by bwbarrett** [comment]
We’ll move today. Sorry about the delay; didn’t realize the deadline was this close.

**Comment by bwbarrett** [comment]
@rhc54 on second thought, we finished the code change and just need our automation to pick it up.  Go ahead and assume we've migrated.  Worst case, we miss one day of testing.

**Comment by rhc54** [comment]
Thanks!

**Pull request merged**
