### PR TITLE
Added Environ plugin which enables setting environment variables.

### PR DESCRIPTION
**Pull request by noahv**
Signed-off-by: Noah van Dresser <daniel.n.van.dresser@intel.com>

### CODE REVIEW

**Comment by rhc54** [comment]
I don't think that is quite correct - you really don't want to have to list every value in the module "options" area. All you really need is something like this:

```python
kvkeys = keyvals.key()
for kvkey in kvkeys:
    os.environ[kvkey] = keyvals[kvkey]
```

This way, every "key = value" pair will be pushed into the environment, not just the ones we hardcoded into the plugin.

Make sense?

**Comment by noahv** [comment]
Sure, we can make it more flexible.   I will update the pull request.

Thanks,

  -- Noah

**Comment by noahv** [comment]
@DebRez I added an easy two line fix for the io.StringIO.seek() instead of StringIO.StringIO.len().
Please take a peak.

Thanks,

  -- Noah

**Comment by rhc54** [comment]
Looks fine to me

**Comment by DebRez** [comment]
Looks good to me, the os.seek and seek_end are compatible with python 2 and
3.

Deb

On Fri, Jul 15, 2016 at 12:10 AM, Noah van Dresser <notifications@github.com

**Pull request merged**
