### PR TITLE
Combinatorial executor

### PR DESCRIPTION
**Pull request by DebRez**
This update includes the basic combinatorial executor, fixes the --skip-sections and --sections options and adds a very basic travis-ci test.

When run the temporary .ini files created by the program are not automatically deleted right now so we can do troubleshooting.  This can be fixed by uncommenting out the next to last line in the pymtt.py file. 

@rhc54 
@noahv 
@hppritcha

### CODE REVIEW

**Comment by noahv** [comment]
Hi Deb, thanks for working on the combinatorial executor. 

Here is my initial feedback on this patch. Can we discuss the questions below in the meeting on Wednesday?  

- I had expected the logic to break apart an ini file into a collection of combinations to be run to be in the Tools/Executor/combinatorial.py plugin.  This patch has that logic in the TestDef parsing instead.  If possible I would like to keep the TestDef logic as simple as possible as all mtt flows need to go through that logic.  Was there a requirement to make those changes in TestDef?

-  You will want to squash this down to a single commit or maybe a few.

- Prints should use the logger.verbose_print routine 

- Please avoid commented out code in commits

- Most of the *.ini files I run on a nightly basis don't function correctly with this code base and instead end up with a an empty reconstituted *.ini file.
```
{}
/tmp/tmpvke1Hc
```
This ran w/o issue:  /opt/mtt/pyclient/pymtt.py --base-dir=/opt/mtt/pylib/ --verbose /opt/mtt/samples/python/ompi_hello_world.ini

Thanks,

  -- Noah

PS Here is one of the failing ini files.  I have not yet pushed this up.  This .ini tests the ability for mtt to properly indicate a test failure as well as capture stdout and stderr.

/opt/mtt/pyclient/pymtt.py --base-dir=/opt/mtt/pylib/ --verbose /opt/mtt/tests/bat/negative.ini

```
pluto1:/opt/mtt/tests/bat # cat negative.ini 
#Copyright (c) 2016      Intel, Inc.  All rights reserved.
#

# Set defaults
[MTTDefaults]
scratch = mttscratch
description = MTT negative BAT test

#======================================================================
# Test get phases - get the tests that the
# target software will run.
#======================================================================

[TestGet:Negative]
plugin = Copytree
src = /opt/mtt/tests/bat

#======================================================================
# Test run phase
#----------------------------------------------------------------------
[TestRun:Negative]
plugin = Shell
parent = TestGet:Negative
save_stdout_on_success = 1
merge_stdout_stderr = 0
stdout_save_lines = 100
stderr_save_lines = 100
command = ./negative.sh

#======================================================================
# Reporter phase
#======================================================================
[Reporter:TextFileConsole]
plugin = TextFile

#======================================================================
# Reporter phase
#======================================================================
[Reporter:JunitXML]
plugin = JunitXML
filename = negative.xml
```
```
pluto1:/opt/mtt/tests/bat # cat negative.sh 
#!/bin/bash -e

echo "negative test stdout"
echo "negative test stderr" >&2
false
```

**Comment by hppritcha** [comment]
@DebRez I think we need to check these commits.  I'm not sure, for instance, that we want the .travis.yml changes in this PR.

**Comment by noahv** [comment]
Hi Deb, I pushed the negative.ini and negative.sh to mtt/tests/bat.  Thanks,  -- Noah

**Comment by DebRez** [comment]
Moving combinatorial code to a different file

**Pull request closed without merging**
